### PR TITLE
BLS12-381 for degrees up to 2^15

### PR DESCRIPTION
**Pull request by sauliusgrigaitis**
Added support for degrees up to 2^15 on BLS12-381.

### CODE REVIEW

**Comment by wborgeaud** [comment]
Very cool, thanks for finding this curve!
Can I ask how you found it?

**Comment by sauliusgrigaitis** [comment]
Brute force :)

**Comment by wborgeaud** [comment]
> Brute force :)

Using Sage?

**Comment by sauliusgrigaitis** [comment]
Yes, Sage sometimes works for brute force :)

**Comment by sauliusgrigaitis** [comment]
Thanks for ultra fast merge!

**Comment by wborgeaud** [comment]
Thanks for the PR! :)

**Comment by asanso** [comment]
@sauliusgrigaitis  @wborgeaud  in case you are looking for better parameters you can find up to 2^64 in the Bandersnatch's paper Table 2 https://eprint.iacr.org/2021/1152.pdf

**Pull request merged**
